In [6]:
import pandas as pd
import mysql.connector
import matplotlib.pyplot as plt

# Configuración de conexión a MySQL
conexion = mysql.connector.connect(
    host="db",                # Cambia a 'localhost' si no estás usando Docker
    user="root",              # Reemplazar por tu usuario de MySQL
    password="rootpassword",  # Reemplazar por tu contraseña de MySQL
    database="ETL"            # Asegúrate de que el nombre de la base de datos sea correcto
)

# Función para ejecutar una consulta SQL y retornar un DataFrame
def ejecutar_consulta(query):
    cursor = conexion.cursor()
    cursor.execute(query)
    resultados = cursor.fetchall()
    columnas = [desc[0] for desc in cursor.description]
    cursor.close()
    return pd.DataFrame(resultados, columns=columnas)

# Ventas totales por producto
query_ventas_por_producto = """
    SELECT producto, SUM(cantidad) as total_cantidad
    FROM ventas
    GROUP BY producto
    ORDER BY total_cantidad DESC
"""
df_ventas_por_producto = ejecutar_consulta(query_ventas_por_producto)

# Ingresos totales por producto
query_ingresos_por_producto = """
    SELECT producto, SUM(cantidad * precio) as total_ingresos
    FROM ventas
    GROUP BY producto
    ORDER BY total_ingresos DESC
"""
df_ingresos_por_producto = ejecutar_consulta(query_ingresos_por_producto)

# Ventas mensuales totales
query_ventas_mensuales = """
    SELECT DATE_FORMAT(fecha, '%Y-%m') as mes, SUM(cantidad) as total_cantidad
    FROM ventas
    GROUP BY mes
    ORDER BY mes
"""
df_ventas_mensuales = ejecutar_consulta(query_ventas_mensuales)

# Producto más vendido
query_producto_mas_vendido = """
    SELECT producto, SUM(cantidad) as total_cantidad
    FROM ventas
    GROUP BY producto
    ORDER BY total_cantidad DESC
    LIMIT 1
"""
df_producto_mas_vendido = ejecutar_consulta(query_producto_mas_vendido)

# Ingresos totales
query_ingresos_totales = """
    SELECT SUM(cantidad * precio) as total_ingresos
    FROM ventas
"""
df_ingresos_totales = ejecutar_consulta(query_ingresos_totales)

# Cerrar la conexión a MySQL
conexion.close()

Ventas totales por producto:
     producto total_cantidad  producto_num
0    Monitor          15705             2
1  Impresora          15402             0
2     Tablet          15141             4
3     Laptop          15107             1
4      Mouse          14991             3
5   Teléfono          14161             6
6    Teclado          13991             5

Ingresos totales por producto:
     producto  total_ingresos  producto_num
0     Laptop    1.666462e+07             1
1   Teléfono    7.099207e+06             6
2     Tablet    4.940794e+06             4
3    Monitor    3.925764e+06             2
4  Impresora    2.565308e+06             0
5    Teclado    4.606047e+05             5
6      Mouse    3.007373e+05             3

Ventas mensuales totales:
         mes total_cantidad
0   2023-01           9204
1   2023-02           8007
2   2023-03           9879
3   2023-04           8547
4   2023-05           8921
5   2023-06           8250
6   2023-07           8784
7   2023-08           8467
8   2023-09           8559
9   2023-10           9114
10  2023-11           7939
11  2023-12           8827

Producto más vendido:
   producto total_cantidad
0  Monitor          15705

Ingresos totales:
    total_ingresos
0    3.595704e+07

TypeError: no numeric data to plot